### PR TITLE
Support CamelCase style auto completion

### PR DESCRIPTION
**Pull request by xqliu**
Let user do auto completion like in idea/eclipse using CamelCase match, 

So user can just input "aVLMN" to get candidate "aVeryLongMethodName" popup, more generally, "aV(ery)L(long)M(ethod)N(name)" matches "aVeryLongMethodName".

This enhancement is suppose to work only if mopemope/meghanada-emacs#99 been merged

Also fixed an issue when lucene index error causes static member completion fail.

### CODE REVIEW

**Comment by xqliu** [comment]
Dear, 

I was also thought about using the getFuzzyDistance method,  but since it is case insensitive, so it will not be able to get the camel case match logic, also, sometimes it gives out too much not relevant result in the list. 

As of CamelCase auto completion, what matches to aVeryLongMethodName will include(but not limit to)

* aVerLMN
* aVLonMN
* aVLoMeNa

So it gives user a lot of flexible for what letter to type.

I will add a config for this feature and submit PR again, thanks for your review :)

**Comment by mopemope** [comment]
> I was also thought about using the getFuzzyDistance method, but since it is case insensitive, so it will not be able to get the camel case match logic, also, sometimes it gives out too much not relevant result in the list.
OK I see.

**Comment by xqliu** [comment]
Dear,

Have updated based on your reviews as below:

1. Add config camel-case-completion: whether to use camel case completion
2. Cache the pattern and match result to boost complete speed.

**Comment by mopemope** [comment]
@xqliu Merged ! Thanks !

**Pull request merged**
